### ISSUE TITLE
`aggTrades` works incorrectly

### ISSUE THREAD

**Issue by szmarczak** [binance/binance-spot-api-docs#10]
According to the docs:

> Trades that fill at the time, from the same taker order, with the same price will have the quantity aggregated.

The first part (`Trades that fill at the time`) is false. Here's an example:

1. https://api.binance.com/api/v3/aggTrades?symbol=NEBLBTC&limit=1000&startTime=1609609200000&endTime=1609609440000
2. https://api.binance.com/api/v3/aggTrades?symbol=NEBLBTC&limit=1000&startTime=1609609200000&endTime=1609612800000

Do note the start time in both cases is the same, only end time differs. So the first trade returned by both calls should be the same. It isn't. The first order time from no 1 is 16096`09203988` while from no 2 it is 16096`10589954`.

**Comment by szmarczak** [comment]
Changing the `limit` parameter also gives weird results.

**Comment by szmarczak** [comment]
> Changing the limit parameter also gives weird results.

Ah, because the `limit` counts from the end. This should have been properly documented.

**Comment by 2pd** [comment]
thank you for the feedback, records are returned in ascending order from spot market endpoints.

**Comment by szmarczak** [comment]
> records are returned in ascending order from spot market endpoints.

How does this relate to the issue? Anyway, I have already noticed this. See my question in the very first comment:

> Do note the start time in both cases is the same, only end time differs. So the first trade returned by both calls should be the same. It isn't. The first order time from no 1 is 1609609203988 while from no 2 it is 1609610589954.

I asked about the time difference. I think that the `limit` property counts from the end. So it limits the amount from 1609609440000 (later) to 1609609200000 (later) and gives the result (as you noted) in an ascending order.

The docs is missing the part that the limit property counts from the endTime to startTime and not the other way.

**Comment by szmarczak** [comment]
It's quite confusing as in all other routes the limit property counts from startTime to endTime.

**Comment by ioan555** [comment]
fff
