### ISSUE TITLE
Add a `precision` parameter to `depth`

### ISSUE THREAD

**Issue by szmarczak** [binance/binance-spot-api-docs#11]
That way it would be possible get more information about depth without using much weight. The steps would be:

- 0.0000001
- 0.000001
- 0.00001
- 0.0001
- 0.001

**Comment by 2pd** [comment]
which endpoint are you referring please?

**Comment by szmarczak** [comment]
Oh, sorry, I mean https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#order-book

**Comment by 2pd** [comment]
thank you for the feedback, we will forward to the team, for now it's recommended to aggregate from the client side.
