### ISSUE TITLE
Some WS subscriptions are not working

### ISSUE THREAD

**Issue by phillijw** [binance/binance-spot-api-docs#14]
1. Go to `https://www.websocket.org/echo.html`
2. Connect to `wss://fstream3.binance.com/ws`
3. Send message: `{"method":"SUBSCRIBE","params":["ethbtc@depth20@0ms"],"id":1}`
4. You will get a response of `{"id":1,"result":null}`
5. Wait and you will see that no data comes back for ethbtc market

Now do the same except try it with market `btcusdt` and data comes streaming back immediately.

**Comment by 2pd** [comment]
Please report production issue to customer support or at https://t.me/binance_api_english
Btw this repo is for spot endpoints only.

**Comment by blacksabbather** [comment]
> 1. Go to `https://www.websocket.org/echo.html`
> 2. Connect to `wss://fstream3.binance.com/ws`
> 3. Send message: `{"method":"SUBSCRIBE","params":["ethbtc@depth20@0ms"],"id":1}`
> 4. You will get a response of `{"id":1,"result":null}`
> 5. Wait and you will see that no data comes back for ethbtc market
> 
> Now do the same except try it with market `btcusdt` and data comes streaming back immediately.

No ethbtc in futures market..

**Comment by 2pd** [comment]
> > 1. Go to `https://www.websocket.org/echo.html`
> > 2. Connect to `wss://fstream3.binance.com/ws`
> > 3. Send message: `{"method":"SUBSCRIBE","params":["ethbtc@depth20@0ms"],"id":1}`
> > 4. You will get a response of `{"id":1,"result":null}`
> > 5. Wait and you will see that no data comes back for ethbtc market
> > 
> > Now do the same except try it with market `btcusdt` and data comes streaming back immediately.
> 
> No ethbtc in futures market..

then you are subscribing to wrong base url, the spot wss url

`wss://stream.binance.com:9443/ws`

**Comment by 2pd** [comment]
have a try with this site: https://2pd.github.io/ws/
