### ISSUE TITLE
Partial Book Depth Streams doesn't tell you what market it's for

### ISSUE THREAD

**Issue by phillijw** [binance/binance-spot-api-docs#15]
If you are subscribed to more than one market on a connection, there is no way to know which market or subscription the Partial Book Depth Streams message is for

**Comment by 2pd** [comment]
subscribe in combined mode with url as 
`wss://stream.binance.com:9443/stream?streams=key1/key2`

![image](https://user-images.githubusercontent.com/365354/104087963-7461ee80-52b7-11eb-8ca0-72d48633ac8d.png)

**Comment by phillijw** [comment]
For anyone else who has this problem, I seem to have a middle of the road workaround:

* Connect using the method suggested by 2pd except don't provide any subscriptions
* Subscribe after connecting using the live subscription method

This seems to provide the necessary data
