### ISSUE TITLE
Endpoint for klines/chandles gives incorrect response

### ISSUE THREAD

**Issue by fruecker** [binance/binance-spot-api-docs#16]
Hello, at first big thanks for that sweet api! 🚀 

While implementing and using it i discovered that the endpoint `/api/v3/klines` gives really odd feedback on all intervals (timeframes). When I am giving it a interval of like `'30m'` which should be 30min candles (right?) and a limit of like 20 it responses me candles with a open and close difference with about 3 weeks! 🤣  Same with other timeframes/intervals.

My code for fetching market_data:
```python
url = self.endpoint + '/api/v3/klines'
if not interval:
    raise ValueError('Error: No interval passed!')
payload = { "symbol" : self.symbol,
            "interval"  : interval}
if limit and type(limit) == int:
    payload.update({ "limit" : limit })
    
r = self.req_get(url, payload=payload)
```
On `self.req_get()` im basically checking response status, etc.

Got my knowledge from [here](https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data)
What the heck i am missing here guys?

Thanks in advance! 🔥 
![Bildschirmfoto von 2021-01-06 23-41-57](https://user-images.githubusercontent.com/29492176/103831169-c28aae00-507b-11eb-8068-555fdf240e68.png)

**Comment by 2pd** [comment]
![image](https://user-images.githubusercontent.com/365354/104087824-afafed80-52b6-11eb-861a-8bfa1ae58a9c.png)
It works fine for me to get the correct klines date.

**Comment by fruecker** [comment]
Yep, my fault. Turned out that the time was passed in ms instead of sec as i supposed :)

Thanks anyways! :)
