### ISSUE TITLE
api【https://fapi.binance.com/fapi/v1/exchangeInfo】request failure!

### ISSUE THREAD

**Issue by zhaodongxx** [binance/binance-spot-api-docs#18]
api【https://fapi.binance.com/fapi/v1/exchangeInfo】request failure!

**Comment by jonmotion** [comment]
working for me:
![image](https://user-images.githubusercontent.com/77019901/104108754-7cc22580-52c7-11eb-8cd8-1bb6116cd132.png)

**Comment by 2pd** [comment]
it will be helpful to understand what happened with more details.
This endpoint works fine for us.
