### ISSUE TITLE
Endpoint: /api/v3/myTrades Returns Invalid Symbol for USDCBTC Market

### ISSUE THREAD

**Issue by Cooksauce** [binance/binance-spot-api-docs#22]
Calling the `myTrades` endpoint errors with:
```
code: -1121,
message: invalid symbol
```

This link here proves that that market is valid, but has been disabled:
[https://www.binance.com/en/support/articles/360020702932-binance-will-add-usdc-quote-pairs-into-the-usd%E2%93%88-trading-market-tab](https://www.binance.com/en/support/articles/360020702932-binance-will-add-usdc-quote-pairs-into-the-usd%E2%93%88-trading-market-tab)

How can I retrieve my trades for this disabled market through the API?

**Comment by lucaswalter** [comment]
+1 I'm currently trying to consume the trade history endpoint in order to complete my taxes for this year. Not having the ability to retrieve transactions is a huge issues as I will be reporting gains/losses to the government.

**Comment by 2pd** [comment]
from the link above, it's for futures market. Do you have the original request returned the error?

**Comment by 2pd** [comment]
`USDCBTC` is not a valid spot market symbol, that's why it shows the error.

**Comment by Cooksauce** [comment]
@2pd So I'm clear on this - are you saying `USDCBTC` is not a valid spot market, because it was a futures market?

**Comment by Cooksauce** [comment]
Here's the announcement for the listing of the `USDCBTC` market:
[https://www.binance.com/en/support/announcement/360019828831](https://www.binance.com/en/support/announcement/360019828831)

**Comment by 2pd** [comment]
it could be removed from the current market, checking all available symbols from:

`api/v3/exchangInfo`

**Comment by Cooksauce** [comment]
I don't see it in the `/api/v3/exchangeInfo` response. It seems like it's been entirely removed from the API. If this is the case, how do I fetch my trade history for the `USDCBTC` symbol?

**Comment by 2pd** [comment]
Please contact customer support and see if they can help.

**Comment by lucaswalter** [comment]
Is there really no way to fetch delisted assets? It seems like quite an oversight to not be able to fetch that history. Many people (including myself) have several thousand trades and depend on this to complete our taxes.

**Comment by Cooksauce** [comment]
@2pd They don't respond

**Comment by Cooksauce** [comment]
Is this the appropriate place for this feedback? Is there a better channel for feedback about the API?

**Comment by Cooksauce** [comment]
@2pd Would you mind directing me to the best channel for feedback here?
