### ISSUE TITLE
Best way to calculate sell quantity in js

### ISSUE THREAD

**Issue by smolleyes** [binance/binance-spot-api-docs#23]
Hi! 

Everything is in the title...

What s your function to calculate SELL quantity on the website? There s too many conditions to me...

Need the value to be > 0.001 sometimes 0.0001 if price is > 0.001 we have to give decimal under 100 sats no decimals etc it s really annoying...

So what the clear and simple way to say i have x token quantity sell me 100 ℅ ... What s the quantity (like on the website) 

Thanks!

**Comment by 2pd** [comment]
If you have 0.01 BTC and wish to sell against `BTCUST`,  then `quantity=0.01`.

There are some filters defining the requirements for placing orders, especially the `LOT_SIZE` for this case.
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#lot_size
