### ISSUE TITLE
Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by Th0rgal** [binance/binance-spot-api-docs#24]
Hello there,

I tried several times to perform an order to buy WTC using BTC. The current price was 0.0000101 BTC per WTC, so 0.00001009 should be a valid value, shouldn't it?
These were my params:
{'symbol': 'WTCBTC', 'side': 'BUY', 'type': 'LIMIT', 'timeInForce': 'GTC', 'quantity': '42.13', 'price': '0.00001009'}

And the error!
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<BotsPooler.send_order() done, defined at ./botspooler.py:156> exception=BinanceError('Filter failure: PRICE_FILTER')>

Sincerely,
Thomas

**Comment by 2pd** [comment]
Please check the Symbol filters from API document, https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#percent_price

this `WTCBTC` has a limitation of it's PRICE_FILTER

```json
                {
                    "filterType": "PRICE_FILTER",
                    "minPrice": "0.00000010",
                    "maxPrice": "1000.00000000",
                    "tickSize": "0.00000010"
                }
```
The specific filters data can be found from `/api/v3/exchangeInfo`

**Comment by Th0rgal** [comment]
> Please check the Symbol filters from API document, https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#percent_price
> 
> this `WTCBTC` has a limitation of it's PRICE_FILTER
> 
> ```json
>                 {
>                     "filterType": "PRICE_FILTER",
>                     "minPrice": "0.00000010",
>                     "maxPrice": "1000.00000000",
>                     "tickSize": "0.00000010"
>                 }
> ```
> 
> The specific filters data can be found from `/api/v3/exchangeInfo`

Hello sir,

Thank you for the help, however, this is what I got:
{'multiplierUp': '5', 'multiplierDown': '0.2', 'avgPriceMins': 5}

Is there a reason why tickSize could be missing?
