### ISSUE TITLE
Get all trades without specifying symbol

### ISSUE THREAD

**Issue by marianogappa** [binance/binance-spot-api-docs#25]
The Binance app/website can definitely do this:

<img width="1166" alt="Screenshot 2021-01-18 at 23 28 45" src="https://user-images.githubusercontent.com/1078546/104970885-f1dadc80-59e4-11eb-8dc5-2182c6dff58d.png">

But it seems it's not using the API:
<img width="763" alt="Screenshot 2021-01-18 at 23 29 51" src="https://user-images.githubusercontent.com/1078546/104970951-2058b780-59e5-11eb-8006-ca3d7fcdcdd0.png">

This information is pretty important when developing a bot, because upon startup, a bot must synchronize with the current state of the trades. The current workaround is to make multiple queries, one for each symbol, but this is cumbersome, inefficient, slow and makes the bot more likely to get rate-limited.

There's no way to discover existing positions in new symbols without making one query for every single symbol.

**Comment by 2pd** [comment]
Thank you for the feedback, we don't have ETA for this yet.

For now it's recommended to store new trades messages from websocket stream, then query from local storage. For historical trades,  clients have to go through each symbol and fetch them by each request.
