### ISSUE TITLE
Balance Update

### ISSUE THREAD

**Issue by Th0rgal** [binance/binance-spot-api-docs#26]
Hello there,

I was looking at the balanceUpdate data stream: https://github.com/binance/binance-spot-api-docs/blob/master/user-data-stream.md#balance-update

It is written:
```
Balance Update occurs during the following:

- Deposits or withdrawals from the account
- Transfer of funds between accounts (e.g. Spot to Margin)
```

Does that mean it won't be sent after a trade that changed the balances amount?

Sincerely,
Thomas

**Comment by 2pd** [comment]
If there is trade, the user data stream will push evens:

- `outboundAccountPosition` and 
- `executionReport`
 
the account balance related info is included from `outboundAccountPosition`

**Comment by Th0rgal** [comment]
> If there is trade, the user data stream will push evens:
> 
> * `outboundAccountPosition` and
> * `executionReport`
> 
> the account balance related info is included from `outboundAccountPosition`

But outboundAccountPosition is going to be removed, right? I keep in memory an up to date list of balances.

**Comment by 2pd** [comment]
We have NO change of `outboundAccountPosition` right now.
