### ISSUE TITLE
Issue with the taker long short ratio end point of the api

### ISSUE THREAD

**Issue by ybangaru** [binance/binance-spot-api-docs#27]
Hello, I have been working with the binance API for a while and noticed there's some error when we request the endpoint https://fapi.binance.com/futures/data/ for the taker longshortratio using a specific symbol eg: BTCUSDT, the endpoint response is not as expected, it does work but the number of data points returned are not as expected. 

The request **https://fapi.binance.com/futures/data/takerlongshortRatio?symbol=BTCUSDT&period=1h&limit=500** is supposed to return 500 data points but it only does 42, you can check it from the browser as well. I wonder what the reason could be. Appreciate any help regarding the same. Thank you

**Comment by 2pd** [comment]
it will be forward to the team for review. This is the spot API document repo,  please share the concern of futures with a topic at https://dev.binance.vision/
thank you
