### ISSUE TITLE
How to get active tokens adresses?

### ISSUE THREAD

**Issue by ahmetsekmen** [binance/binance-spot-api-docs#29]
Hello,

I couldn't find how to get list of binance market active tokens adreses. (erc-20)
Like;

aave, 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9
comp, 0xc00e94cb662c3520282e6f5717214004a7f26888
....

**Comment by 2pd** [comment]
Unfortunately token address is not available from API endpoint.
