### ISSUE TITLE
Wallet Address Reset Endpoint

### ISSUE THREAD

**Issue by barhun** [binance/binance-spot-api-docs#5]
Hi, everyone

Is there an API endpoint for resetting addresses of wallets such as that of IOTA? In the website and the mobile app, this is possible; but I wasn't able to find related info in the docs. Thanks in advance.

**Comment by 2pd** [comment]
I don't think there is an API endpoint to reset address, but there is one that can be used to fetch latest available address. 

https://binance-docs.github.io/apidocs/spot/en/#deposit-address-supporting-network-user_data

**Comment by barhun** [comment]
Thanks for the response. (: Well, I'm aware of that one; but what I need is seemingly not available yet.
