### ISSUE TITLE
executionReports in user data stream is significantly delayed

### ISSUE THREAD

**Issue by leftys** [binance/binance-spot-api-docs#9]
Hello, i am creating this bug report as multiple users on telegram @binance_api_english reported that executionReports come delayed compared to other market data messages. The delay between trade messages and executionReports can be up to hundreds of milliseconds.

Example:
This executionReport is correct (~6ms delay):
event_time_ns=T08:27:16.156000000, receive_time=T08:27:16.162796544

This executionReport is slightly delayed (~124 ms delay)
event_time_ns=T16:18:57.329000936, receive_time=T16:18:57.454724352
The trade message corresponding to this fill came with 5ms delay compared to the 124ms. (event_time_ns is the E field of executionReport)

**Comment by 2pd** [comment]
Thank you for the feedback, we are continuously working on improving the performance.
